### ISSUE TITLE
For date "Tue, 17 Mar 2015 19:36:03 -0700" prettydate gives "169 years later" when it is "2015-03-18T03:46:07.255Z"

### ISSUE THREAD

**Issue by danielzfranklin** [fengyuanchen/prettydate#3]
When I give prettydate the date ""Tue, 17 Mar 2015 19:36:03 -0700" prettydate gives "169 years later". Today is "2015-03-18T03:46:07.255Z" ( JSON.stringify(new Date()) ). What could be happening?

**Comment by fengyuanchen** [comment]
You should remove the ` -0700`, it seems to be a timezone.

**Comment by danielzfranklin** [comment]
Is there a simple way to convert the date to the user's timezone? 
Thank you, 
Daniel

**Comment by fengyuanchen** [comment]
You may output the date with JavaScript (new Date()) in user's browser, or find a project for converting date on github.

**Comment by danielzfranklin** [comment]
Thank you

On Mar 17, 2015, "Fengyuan Chen [Masked]" <FWD_JK8bXfyR@opayq.com> wrote:
>
>
>
>
>You may output the date with JavaScript (new Date()) in user's browser,
>or find a project for converting date on github.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/fengyuanchen/prettydate/issues/3#issuecomment-82738406

-----

The glass is neither half-full nor half-empty: it's twice as big as it needs to be. 

Daniel Franklin
15b5cafd@opayq.com
danielzfranklin.com

**Comment by danielzfranklin** [comment]
Send me a F#ckFriends request so we can hook up
My usename is Merlin610
my profile is here ONLINE NOW

**Comment by danielzfranklin** [comment]
Send me a F#ckFriends request so we can hook up
My usename is SexyBear429
my profile is here TALK S00N

**Comment by danielzfranklin** [comment]
Send me a F#ckFriends request so we can hook up
My usename is LittleKinky364
my profile is here :)

**Comment by danielzfranklin** [comment]
Send me a F#ckFriends request so we can hook up
My usename is LittleMonkey208
my profile is here IM ONLINE

**Comment by fengyuanchen** [comment]
@danielzfranklin What the heck!

**Comment by danielzfranklin** [comment]
From the time you first tried Viagra Soft you'll never forget these moments! Make up your mind now! Purchase now!
Viagra Soft - widely known in narrow circles. It's time for you to get one of them. 

You can buy in our online drugstore!

Viagra Soft � you can rely on our professional help. Purchase at our online shop now!
Your interest will grow as our prices are low! Purchase now! Viagra Soft at our online shop now!
Viagra Soft � softly sets you ready for a long action. 

Available on our online shop now!

**Comment by danielzfranklin** [comment]
One of the bestsellers awaits for its lucky owner on our online shop. Viagra Professional might be yours! Buy now.
Cram more into your sex abilities list. Viagra Professional in our online shop is affordable like never before!

Greatest hit! Worth to admit. Viagra Professional for you in our online shop!

Get what you have been dreaming a long time and more with Viagra Professional. Buy in our online shop!
Be a professional in love! 
Buy Viagra Professional at our online shop!

**Comment by danielzfranklin** [comment]
Shop now with us! Cialis Professional is popular like no other! Buy online!
Our price on Cialis Professional makes it is easy to figure out where to buy it!
You're up all night to get lucky! Cialis Professional you can't miss the moment! Try it now! 

Purchase in our online shop!

Cialis Professional - any remedy won't take care of your sex health better. Any drugstore will offer it cheeper!
Explore your love abilities! Believe they can be endless with Cialis Professional. 

You can purchase it in our online shop. It's easy!
